CXX=g++
GTEST_FLAGS=-lgtest -lpthread

.PHONY: dna rna revc gc hamm

all: dna rna revc gc hamm

dna:
	$(CXX) DNA/DNA.cpp -o DNA/dna

rna:
	$(CXX) RNA/RNA.cpp -o RNA/rna

revc:
	$(CXX) REVC/REVC.cpp -o REVC/revc

gc:
	$(CXX) GC/GC.cpp -o GC/gc

hamm:
	$(CXX) HAMM/HAMM.cpp -o HAMM/hamm
