CC=g++
CFLAGS=-g -Wall

blinky:
	$(CC) $(CFLAGS) -o blinky thinkpad_blinky.cpp

sysinfo:
	$(CC) $(CFLAGS) -o sysinfo linux_sysinfo.cpp

tempconverter:
	$(CC) $(CFLAGS) -o tempconverter temp_converter.cpp

taxbrackets:
	$(CC) $(CFLAGS) -o taxbrackets tax_brackets.cpp
